### ISSUE TITLE
osx environment on travis

### ISSUE THREAD

**Issue by cognitom** [iDuuck/sketchjs#2]
Using osx for node.js application is not recommended by Travis, but it could be useful in this case:

``` yaml
os:
  - osx
before_install:
  - npm install -g gulp
  - curl -L https://raw.githubusercontent.com/cognitom/dotfiles/master/lib/sketchtool.sh | sudo sh
install: npm install
script: npm test
```

I'm using this in `gulp-sketch`.
https://github.com/cognitom/gulp-sketch/blob/master/.travis.yml

If you like it, I'll send PR soon.
BTW, your try is great! I'd like to use this from my gulp plugins.
